version: '2'

services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.development
    environment:
      - DISABLE_NOTIFIER=true
    volumes:
      - .:/code
      - /code/node_modules
    ports:
      - '8080:8080'